package com.example.codepolyglot;

public class LanguageTools {
    public static String[] languages = {
            "1C",
            "A",
            "ActionScript",
            "Ada",
            "AmbientTalk",
            "Assembly",
            "B",
            "Bash",
            "BASIC",
            "C",
            "C++",
            "COBOL",
            "CoffeeScript",
            "Eiffel",
            "Elixir",
            "Erlang",
            "F",
            "F#",
            "Fortran",
            "Go",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Kotlin",
            "LINQ",
            "Lisp",
            "Lua",
            "MATLAB",
            "Objective-C",
            "Pascal",
            "Perl",
            "PHP",
            "PowerShell",
            "Prolog",
            "Python",
            "Ruby",
            "Rust",
            "Scala",
            "Smalltalk",
            "SQL",
            "Swift",
            "TypeScript",
            "VHDL",
            "Visual Basic",
            "WebAssembly"
    };
}
